name: Deploy to github pages
on:
  push:
    branhces: ["main"]
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.DEPLOY_KEY }}

jobs:
  # Build site
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Config
      run: |
        git config --global user.email "mungarifr@gmail.com"
        git config --global user.name "Birbatron"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        yarn insyall package.json
    - name: Deploy
      run: npm run deploy-ci